server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: beans, health, loggers
    health:
      enabled: true
    loggers:
      enabled: true
    beans:
      enabled: true

logging:
  level.io.fdlessard.codebites.jpaflush: debug
  level.root: debug
  level.org.hibernate.SQL: info

spring:
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
    serialization:
      write_dates_as_timestamps: false
  sql:
    init:
      platform: postgres
      mode: never
  datasource:
    username: postgres
    password: secret
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      jdbc:
        time_zone: UTC
    show-sql: true
  liquibase:
    enabled: on
    drop-first: on
    default-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml

